name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      # Docker-in-Docker so we can run docker commands
      docker:
        image: docker:24.0.6-dind
        options: >-
          --privileged
          --network host
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & start services
        working-directory: ./docker
        run: |
          docker-compose up --build -d

      - name: Wait for SQL Server to be ready
        run: |
          for i in $(seq 1 15); do
            docker run --network host --rm mcr.microsoft.com/mssql-tools \
              /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1,1433 -U sa -P "Your_strong_P@ssw0rd" -Q "SELECT 1" \
              && break || sleep 5
          done

      - name: Smoke test — hit OrderService health endpoint
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 5 \
            http://localhost:5001/health || exit 1

      - name: Smoke test — hit ProductService health endpoint
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 5 \
            http://localhost:5002/health || exit 1

      - name: Smoke test — hit IdentityService health endpoint
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 5 \
            http://localhost:5003/health || exit 1

      - name: Tear down
        working-directory: ./docker
        run: |
          docker-compose down -v

