name: Docker Compose CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6-dind
        options:
          - --privileged
        ports:
          - 2375:2375

    env:
      DOCKER_HOST: tcp://localhost:2375

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Build & start services
        working-directory: ./docker
        run: docker-compose up --build -d

      - name: Wait for SQL Server
        run: |
          for i in {1..15}; do
            docker run --rm mcr.microsoft.com/mssql-tools \
              /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa \
              -P "Your_strong_P@ssw0rd" -Q "SELECT 1" && break
            sleep 5
          done

      - name: Smoke test OrderService
        run: curl --fail --retry 5 --retry-delay 5 http://localhost:5001/health

      - name: Smoke test ProductService
        run: curl --fail --retry 5 --retry-delay 5 http://localhost:5002/health

      - name: Smoke test IdentityService
        run: curl --fail --retry 5 --retry-delay 5 http://localhost:5003/health

      - name: Tear down
        working-directory: ./docker
        run: docker-compose down -v
